
export const SOCKET_CONSTANTS = {
    SOCKET_CONN_REQ:'SOCKET_CONN_REQ',
    DISCONNECTED:'DISCONNECTED',
    CONNECTED:'CONNECTED',
    SEND_MSG:'SEND_MSG',
    BROADCAST_MSG:'BROADCAST_MSG',
}

export const USER_EVENT = {
    IS_SUPER_USER_AVAILABLE:'IS_SUPER_USER_AVAILABLE',
    SET_SUPER_USER:'SET_SUPER_USER',
    AVAILABLE_USER:'AVAILABLE_USER',
    EXIT:'AVAILABLE_USER',
    SUPER_USER_IS_AVAILABLE:'SUPER_USER_IS_AVAILABLE',
    SUPER_USER_SET:'SUPER_USER_SET'
}

export const USER_TYPE={
    SUPER:'SUPER_USER',
    USER:'USER'
}